
run.bmstu0302:
	gcc -std=c17 ./1.loadfile.c -o build/1.loadfile  && ./build/1.loadfile

run.bmstu0302.v2:
	gcc -std=c17 ./2.loadfilev2.c -o build/2.loadfilev2  && ./build/2.loadfilev2

run.bmstu0302.v3:
	gcc -std=c17 ./3.loadfilev3.c -o build/3.loadfilev3  && ./build/3.loadfilev3

run.bmstu0302.v4:
	gcc -std=c17 ./4.loadfilev4.c -o build/4.loadfilev4  && ./build/4.loadfilev4

run.bmstu0302.v5:
	gcc -std=c17 ./5.loadfilev5.c -o build/5.loadfilev5  && ./build/5.loadfilev5

run.bmstu0302.v6:
	gcc -std=c17 ./6.1.loadfilev6.c -o build/6.1.loadfilev6  && ./build/6.1.loadfilev6