
run.bmstu0302:
	gcc -std=c17 ./1.loadfile.c -o build/1.loadfile  && ./build/1.loadfile

run.bmstu0302.v2:
	gcc -std=c17 ./2.loadfilev2.c -o build/2.loadfilev2  && ./build/2.loadfilev2

run.bmstu0302.v3:
	gcc -std=c17 ./3.loadfilev3.c -o build/3.loadfilev3  && ./build/3.loadfilev3