
run.bmstu0501.v6:
	gcc -std=c17 ./6.loadfilev6.c -lsqlite3 -o build/6.loadfilev6  && ./build/6.loadfilev6

run.bmstu0501.databasetest:
	gcc -std=c17 ./databasetest.c -lsqlite3 -o build/databasetest  && ./build/databasetest

run.bmstu0501.v7:
	gcc -std=c17 ./7.loadfilev7.c -lsqlite3 -o build/7.loadfilev7  && ./build/7.loadfilev7
