
run.bmstu0301.2:
	gcc -std=c17 ./2.jsontest.c -ljson-c -o build/2.jsontest  && ./build/2.jsontest 
# статика адресуется для ./2.jsontest.c, это делает сам сборщик MAKE. 
# если обращаться непосредственно к файлу в папке build, то файлы статики нужно скопировать туда
